CREATE SEQUENCE public.s_merge_histo_id;

CREATE TABLE public.MERGE_HISTO (
	ID INTEGER NOT NULL DEFAULT nextval('public.s_merge_histo_id'),
	HISTO_DATE TIMESTAMP NOT NULL,
	ALIGNMENT INTEGER NULL,
    PRIMARY_COLOR VARCHAR(7) NOT NULL,
    OUTLINE_COLOR VARCHAR(7) NOT NULL,
    OUTLINE_WIDTH INTEGER NOT NULL,
    FONT_NAME VARCHAR(20) NOT NULL,
    FONT_SIZE INTEGER NOT NULL,
    FK_MERGE_HISTO INTEGER NULL,
    CONSTRAINT pk_merge_histo PRIMARY KEY (ID)
);


ALTER TABLE public.MERGE_HISTO ADD CONSTRAINT merge_histo_id_fk
FOREIGN KEY (FK_MERGE_HISTO)
REFERENCES public.MERGE_HISTO (ID)
ON DELETE NO ACTION	
ON UPDATE NO ACTION
NOT DEFERRABLE;